version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "sqlserver@12345"
    ports:
      - "4000:1433"
    networks:
      - app-network
    volumes:
      - sql-vol:/var/opt/mssql

  dockerproject:
    image: backend:v1
    container_name: backend
    build:
      context: .
      dockerfile: DockerProject/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:8080"
    networks:
      - app-network
    depends_on:
      - sqlserver

networks:
  app-network:
    driver: bridge

volumes:
  sql-vol: